#!/usr/bin/env bash

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

SPECFILE="quicken-kvm-access.spec"

set -e

#  Get the full path to the spec file
SPECFILE=$(dirname "$(realpath "$0")")/$SPECFILE

#  Parse the package name, version and release out of the spec file
NAME=$(sed -n 's/^Name:[[:space:]]*//p' "$SPECFILE")
VERSION=$(sed -n 's/^Version:[[:space:]]*//p' "$SPECFILE")
RELEASE=$(sed -n 's/^Release:[[:space:]]*//;s/%{?dist}//p' "$SPECFILE")
ARCH=$(sed -n 's/^BuildArch:[[:space:]]*//p' "$SPECFILE")

if [ $(cat /etc/hostname) == "fang.localdomain" ]; then
	echo "Building $NAME in fedora-rpmbuild:31 container ..."
	podman run --interactive --name=rpmbuild --rm --tty --volume=${HOME}:${HOME} localhost/fedora-rpmbuild:31 "$(realpath "$0")"

	echo -e "\nTest installation of ${NAME}-${VERSION}-${RELEASE}.fc31.${ARCH}.rpm in fedora-rpmbuild:31 container ..."
	podman run --interactive --name=rpmbuild --rm --tty --volume=${HOME}:${HOME} localhost/fedora-rpmbuild:31 dnf install -y ${HOME}/rpmbuild/RPMS/${ARCH}/${NAME}-${VERSION}-${RELEASE}.fc31.${ARCH}.rpm
	
	echo -e "\nSending source RPM to COPR build ..."
	copr-cli build ${NAME} ${HOME}/rpmbuild/SRPMS/${NAME}-${VERSION}-${RELEASE}.fc31.src.rpm
	
else
	echo -e "\nUpdate system software ..."
	dnf -y upgrade

	#  Put the source files into place
	SOURCE0=$(sed -n 's/^Source0:[[:space:]]*//p' "$SPECFILE")
	SOURCE0=$(echo "$SOURCE0" | sed "s/%{name}/${NAME}/;s/%{version}/${VERSION}/")
	X=$(dirname "$SPECFILE")
	tar -zcvf "${HOME}/rpmbuild/SOURCES/${SOURCE0}" --transform="s|${X#/}|${NAME}-${VERSION}|" $(dirname "$SPECFILE")/${NAME}* $(dirname "$SPECFILE")/LICENSE

	#  Build the packages.  Try twice, in case of an Access Exception, which happens occasionally
	if ! rpmbuild -ba "$SPECFILE"; then
		echo -e "\nrpmbuild failed, retrying rpmbuild ..."
		rpmbuild -ba "$SPECFILE"
	fi

	echo -e "\nCopying RPM files to host system ..."
	mv ${HOME}/rpmbuild/RPMS/${ARCH}/${NAME}-${VERSION}-${RELEASE}.*.${ARCH}.rpm /home/dlk/rpmbuild/RPMS/${ARCH}/
	mv ${HOME}/rpmbuild/SRPMS/${NAME}-${VERSION}-${RELEASE}.*.src.rpm /home/dlk/rpmbuild/SRPMS/
fi
